------------------------------------------------------------
-- USERS TABLE 
------------------------------------------------------------
CREATE TABLE users (
    cnic            VARCHAR2(25) PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL,
    email           VARCHAR2(100) UNIQUE NOT NULL,
    password        VARCHAR2(200) NOT NULL,
    phone           VARCHAR2(20)
);

------------------------------------------------------------
-- ORGANISER TABLE  (password added)
------------------------------------------------------------
CREATE TABLE organiser (
    organiser_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL,
    email_address   VARCHAR2(100) UNIQUE NOT NULL,
    password        VARCHAR2(200) NOT NULL
);

------------------------------------------------------------
-- VENUE TABLE
------------------------------------------------------------
CREATE TABLE venue (
    venue_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_name      VARCHAR2(200) NOT NULL,
    address         VARCHAR2(200) NOT NULL,
    city            VARCHAR2(100),
    capacity        NUMBER NOT NULL
);

------------------------------------------------------------
-- EVENT TABLE
------------------------------------------------------------
CREATE TABLE event (
    event_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organiser_id    NUMBER NOT NULL,
    venue_id        NUMBER NOT NULL,
    title           VARCHAR2(150) NOT NULL,
    category        VARCHAR2(100),
    event_date      DATE NOT NULL,
    start_time      VARCHAR2(10),
    end_time        VARCHAR2(10),
    ticket_price    NUMBER NOT NULL,
    allocated_seats NUMBER NOT NULL,
    status          VARCHAR2(30) DEFAULT 'UPCOMING',

    CONSTRAINT fk_event_organiser FOREIGN KEY (organiser_id)
        REFERENCES organiser(organiser_id),

    CONSTRAINT fk_event_venue FOREIGN KEY (venue_id)
        REFERENCES venue(venue_id)
);

------------------------------------------------------------
-- BOOKING TABLE 
------------------------------------------------------------
CREATE TABLE booking (
    booking_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnic            VARCHAR2(25) NOT NULL,
    event_id        NUMBER NOT NULL,
    booking_date    DATE DEFAULT SYSDATE,
    num_tickets     NUMBER NOT NULL,
    total_amount    NUMBER NOT NULL,
    status          VARCHAR2(20) DEFAULT 'PENDING',

    CONSTRAINT fk_booking_user FOREIGN KEY (cnic)
        REFERENCES users(cnic),

    CONSTRAINT fk_booking_event FOREIGN KEY (event_id)
        REFERENCES event(event_id)
);

------------------------------------------------------------
-- PAYMENT TABLE
------------------------------------------------------------
CREATE TABLE payment (
    payment_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      NUMBER NOT NULL UNIQUE,
    payment_date    DATE DEFAULT SYSDATE,
    total_amount    NUMBER NOT NULL,
    payment_status  VARCHAR2(20) DEFAULT 'PENDING',
    payment_method  VARCHAR2(30),
    transaction_id  VARCHAR2(100),

    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id)
        REFERENCES booking(booking_id)
);

------------------------------------------------------------
-- INDEXES
------------------------------------------------------------
CREATE INDEX idx_booking_user ON booking(cnic);
CREATE INDEX idx_booking_event ON booking(event_id);
CREATE INDEX idx_event_date ON event(event_date);
CREATE INDEX idx_payment_status ON payment(payment_status);

------------------------------------------------------------
-- TRIGGER: Check seats availability
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_check_seats
BEFORE INSERT ON booking
FOR EACH ROW
DECLARE
    seats_left NUMBER;
BEGIN
    SELECT allocated_seats - NVL(SUM(num_tickets),0)
    INTO seats_left
    FROM event e
    LEFT JOIN booking b ON e.event_id = b.event_id
    WHERE e.event_id = :NEW.event_id
    GROUP BY allocated_seats;

    IF seats_left < :NEW.num_tickets THEN
        RAISE_APPLICATION_ERROR(-20001, 'Not enough seats available.');
    END IF;
END;
/
------------------------------------------------------------
-- TRIGGER: Auto set PAID when amount matches
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_auto_payment_status
BEFORE INSERT OR UPDATE ON payment
FOR EACH ROW
DECLARE
    booking_amt NUMBER;
BEGIN
    SELECT total_amount INTO booking_amt
    FROM booking
    WHERE booking_id = :NEW.booking_id;

    IF :NEW.total_amount = booking_amt THEN
        :NEW.payment_status := 'PAID';
    END IF;
END;
/

------------------------------------------------------------
-- VIEWS
------------------------------------------------------------
CREATE OR REPLACE VIEW upcoming_events_view AS
SELECT 
    e.event_id,
    e.title,
    e.category,
    e.event_date,
    e.start_time,
    e.end_time,
    e.ticket_price,
    v.venue_name,
    v.city,
    o.name AS organiser_name
FROM event e
JOIN venue v ON e.venue_id = v.venue_id
JOIN organiser o ON e.organiser_id = o.organiser_id
WHERE e.status = 'UPCOMING';

CREATE OR REPLACE VIEW user_booking_summary AS
SELECT 
    u.cnic,
    u.name,
    b.booking_id,
    b.booking_date,
    b.num_tickets,
    b.total_amount,
    e.title AS event_title,
    p.payment_status
FROM users u
LEFT JOIN booking b ON u.cnic = b.cnic
LEFT JOIN event e ON b.event_id = e.event_id
LEFT JOIN payment p ON p.booking_id = b.booking_id;

------------------------------------------------------------
-- STORED PROCEDURE
------------------------------------------------------------
CREATE OR REPLACE PROCEDURE create_booking (
    p_cnic IN VARCHAR2,
    p_event_id IN NUMBER,
    p_num_tickets IN NUMBER,
    p_payment_method IN VARCHAR2
) AS
    v_price NUMBER;
    v_booking_id NUMBER;
BEGIN
    SELECT ticket_price INTO v_price
    FROM event
    WHERE event_id = p_event_id;

    INSERT INTO booking(cnic, event_id, num_tickets, total_amount)
    VALUES(p_cnic, p_event_id, p_num_tickets, v_price * p_num_tickets)
    RETURNING booking_id INTO v_booking_id;

    INSERT INTO payment(booking_id, total_amount, payment_method)
    VALUES(v_booking_id, v_price * p_num_tickets, p_payment_method);

    COMMIT;
END;
/

------------------------------------------------------------
-- SAMPLE DATA
------------------------------------------------------------

-- USERS
INSERT INTO users VALUES ('42101-1234567-1', 'Ayesha Khan', 'ayesha@gmail.com', 'pass123', '03001234567');
INSERT INTO users VALUES ('42101-7654321-9', 'Ahmed Ali', 'ahmed@gmail.com', 'pass123', '03011223344');
INSERT INTO users VALUES ('42101-9999999-0', 'Sara Malik', 'sara@gmail.com', 'pass123', '03015556677');
INSERT INTO users VALUES ('42101-8888888-5', 'Bilal Ahmed', 'bilal@gmail.com', 'pass123', '03112223344');

-- ORGANISERS (password included)
INSERT INTO organiser (name, email_address, password) VALUES ('EventCorp', 'contact@eventcorp.com', 'pass123');
INSERT INTO organiser (name, email_address, password) VALUES ('Star Events', 'info@starevents.com', 'pass123');
INSERT INTO organiser (name, email_address, password) VALUES ('FunTime Management', 'support@funtime.com', 'pass123');

-- VENUES
INSERT INTO venue (venue_name, address, city, capacity) VALUES ('Expo Center Hall A', 'Main Shahrah-e-Faisal', 'Karachi', 5000);
INSERT INTO venue (venue_name, address, city, capacity) VALUES ('City Auditorium', 'University Road', 'Karachi', 1200);
INSERT INTO venue (venue_name, address, city, capacity) VALUES ('Royal Arena', 'Downtown Boulevard', 'Lahore', 8000);

-- EVENTS
INSERT INTO event (organiser_id, venue_id, title, category, event_date, start_time, end_time, ticket_price, allocated_seats) 
VALUES (1, 1, 'Tech Conference 2025', 'Technology', DATE '2025-12-20', '10:00', '18:00', 2000, 3000);

INSERT INTO event (organiser_id, venue_id, title, category, event_date, start_time, end_time, ticket_price, allocated_seats)
VALUES (2, 2, 'Music Fest Live', 'Music', DATE '2025-12-25', '19:00', '23:00', 3000, 1000);

INSERT INTO event (organiser_id, venue_id, title, category, event_date, start_time, end_time, ticket_price, allocated_seats)
VALUES (3, 3, 'Art and Culture Expo', 'Exhibition', DATE '2025-12-18', '12:00', '20:00', 1500, 1500);

-- BOOKINGS
INSERT INTO booking (cnic, event_id, booking_date, num_tickets, total_amount, status)
VALUES ('42101-1234567-1', 1, DATE '2025-11-30', 2, 4000, 'CONFIRMED');

INSERT INTO booking (cnic, event_id, booking_date, num_tickets, total_amount, status)
VALUES ('42101-7654321-9', 2, DATE '2025-11-30', 1, 3000, 'CONFIRMED');

INSERT INTO booking (cnic, event_id, booking_date, num_tickets, total_amount, status)
VALUES ('42101-9999999-0', 3, DATE '2025-11-30', 3, 4500, 'PENDING');

-- PAYMENTS
INSERT INTO payment (booking_id, payment_date, total_amount, payment_status, payment_method, transaction_id)
VALUES (1, DATE '2025-11-30', 4000, 'PAID', 'Credit Card', 'TXN1001');

INSERT INTO payment (booking_id, payment_date, total_amount, payment_status, payment_method, transaction_id)
VALUES (2, DATE '2025-11-30', 3000, 'PAID', 'EasyPaisa', 'TXN1002');

INSERT INTO payment (booking_id, payment_date, total_amount, payment_status, payment_method, transaction_id)
VALUES (3, DATE '2025-11-30', 4500, 'PENDING', 'JazzCash', 'TXN1003');

COMMIT;
